import { NgModule } from '@angular/core';
import { CommonModule as CModule } from '@angular/common';
import {
    MatRadioModule,
    MatButtonModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatSidenavModule,
    MatListModule,
    MatFormFieldModule,
    MatInputModule,
    MatSnackBarModule,
    MAT_SNACK_BAR_DEFAULT_OPTIONS,
    MatChipsModule,
    MatExpansionModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatTableModule,
    MatPaginatorModule,
    MatSelectModule,
    MatCheckboxModule,
    MatIcon,
    MatBadgeModule,
    MatAutocompleteModule,
    MatTabsModule,
    MatSortModule,
    MatStepperModule
  } from '@angular/material';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

@NgModule({
    imports: [
        FormsModule,
        ReactiveFormsModule,
        // SpinnerModule,
        // MomentModule,
        MatRadioModule,
        MatButtonModule,
        MatStepperModule,
        MatMenuModule,
        MatToolbarModule,
        MatIconModule,
        MatSidenavModule,
        MatListModule,
        MatCardModule,
        MatInputModule,
        MatSnackBarModule,
        MatChipsModule,
        MatExpansionModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatTableModule,
        MatPaginatorModule,
        MatSelectModule,
        MatCheckboxModule,
        MatBadgeModule,
        MatAutocompleteModule,
        MatTabsModule,
        MatSortModule,
        CModule,
    ],
    exports: [
        FormsModule,
        ReactiveFormsModule,
        // SpinnerModule,
        // MomentModule,
        MatRadioModule,
        MatButtonModule,
        MatMenuModule,
        MatStepperModule,
        MatToolbarModule,
        MatIconModule,
        MatSidenavModule,
        MatListModule,
        MatCardModule,
        MatInputModule,
        MatSnackBarModule,
        MatChipsModule,
        MatExpansionModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatTableModule,
        MatPaginatorModule,
        MatSelectModule,
        MatCheckboxModule,
        MatBadgeModule,
        MatAutocompleteModule,
        MatTabsModule,
        MatSortModule,
        CModule,
    ]
})
export class CommonModule {}
